### List all employees
GET http://localhost:3000/employees


### Create a new employee
POST http://localhost:3000/employees/new
content-type: application/json

{
  "email": "yifat.br@lusha.com",
  "title": "full stack developer",
  "department": "R&D",
  "salary": 50000,
  "role": "admin"
}


### Get a particular employee
GET http://localhost:3000/employees/guy.l@lusha.com


### Update a particular employee
PATCH http://localhost:3000/employees/guy.l@lusha.com
content-type: application/json

{
  "salary": 100000,
  "role": "superAdmin"
}


### Delete a particular employee
DELETE http://localhost:3000/employees/guy.l@lusha.com